### PR TITLE
Login & Signup page work started

### PR DESCRIPTION
**Pull request by akshat1712**
The following task is started 
1. Login and Signup pages are made. Themes and Styling will be done later as the theme is finalized 
2. State containing user_email and auth token have also been made on the redux toolkit.

### CODE REVIEW

**Review by rishijohri — COMMENTED** [review]
do not use snake case for naming. Use camel case instead. Look at demo code for reference.

**Comment by akshat1712** [comment]
Camel case for both file name and variables?

I should go with which one of the following:
1. CamelCase
2. camelCase

I think it is the second one.

**Comment by tanmayaeron** [comment]
Convention is different for variable name, function name, component, file name.
For variable, function name, file/folder name- camelCase
For component name, name of types - CamelCase

For files containing components it will be CamelCase.

**Comment by akshat1712** [comment]
okay, I will make the required changes.

**Pull request closed without merging**
